version: "3.7"
services:
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
  minio:
    image: docker.io/bitnami/minio:2024
    volumes:
      - minio-data:/bitnami/minio/data
    environment:
      - MINIO_ROOT_USER=pixeleye
      - MINIO_ROOT_PASSWORD=CHANGEME
      - MINIO_DEFAULT_BUCKETS=pixeleye
  postgres:
    build:
      context: ./config
      dockerfile: ./Dockerfile.psql
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=guest
      - POSTGRES_PASSWORD=CHANGEME
      - POSTGRES_DB=guest
      - PGPORT=5431
      - POSTGRES_MULTIPLE_DATABASES=pixeleye,kratos
  rabbitmq:
    image: rabbitmq:3.13
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=CHANGEME
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
  pixeleye-migrate:
    image: pixeleye/pixeleye-migrations:latest
    environment:
      - DB_HOST=postgres
      - DB_PORT=5431
      - DB_NAME=pixeleye
      - DB_USERNAME=guest
      - DB_PASSWORD=CHANGEME
      - DB_PARAMS=sslmode=disable
    restart: on-failure
  pixeleye-backend:
    depends_on:
      - pixeleye-migrate
    image: pixeleye/pixeleye:latest
    restart: unless-stopped
    environment:
      - STAGE_STATUS=prod
      - BACKEND_URL=https://pixeleye-backend.zu.ca
      - FRONTEND_URL=https://pixeleye-frontend.zu.ca
      - DB_HOST=postgres
      - DB_PORT=5431
      - DB_NAME=pixeleye
      - DB_USERNAME=guest
      - DB_PASSWORD=CHANGEME
      - DB_SSL_MODE=disable
      - DB_MAX_CONNECTIONS=20
      - DB_MAX_IDLE_CONNECTIONS=4
      - DB_MAX_LIFTTIME_CONNECTIONS=1
      - S3_BUCKET=pixeleye
      - S3_ENDPOINT=http://minio:9000
      - S3_CLIENT_ENDPOINT=https://pixeleye-minio.zu.ca
      - S3_ACCESS_KEY_ID=pixeleye
      - S3_KEY_SECRET=CHANGEME
      - ORY_URL=https://pixeleye-kratos.zu.ca
      - ORY_ADMIN_URL=https://pixeleye-kratos-admin.zu.ca
      - AMQP_USER=guest
      - AMQP_PASSWORD=CHANGEME
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_VHOST=/
      - AMQP_TLS=false
      - SMTP_HOST=mailslurper
      - SMTP_PORT=1025
      - SMTP_USER=test
      - SMTP_PASSWORD=test
      - SMTP_SENDER=no-reply@pixeleye.sh
      # - GITHUB_APP_NAME= # optional if you want to use the github login
      # - GITHUB_APP_CLIENT_ID= # optional if you want to use the github login
      # - GITHUB_APP_ID= # optional if you want to use the github login
      # - GITHUB_APP_CLIENT_SECRET= # optional if you want to use the github login
      # - GITHUB_APP_PRIVATE_KEY= # optional if you want to use the github login
  pixeleye-frontend:
    image: pixeleye/pixeleye-frontend:latest
    restart: unless-stopped
    environment:
      - ORY_URL=http://kratos:4433
      - CLIENT_ORY_URL=https://pixeleye-kratos.zu.ca
      - NEXT_PUBLIC_BACKEND_URL=http://pixeleye-backend:5000
      # - NEXT_PUBLIC_GITHUB_APP_NAME= # optional if you want to use the github login

  kratos-migrate:
    build:
      context: ./config
      dockerfile: ./Dockerfile.kratos-migrate
    environment:
      - DSN=postgres://guest:CHANGEME@postgres:5431/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    restart: on-failure
  kratos:
    depends_on:
      - kratos-migrate
    build:
      context: ./config
      dockerfile: ./Dockerfile.kratos
    restart: unless-stopped
    environment:
      - DSN=postgres://guest:CHANGEME@postgres:5431/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace

volumes:
  postgres-data:
  rabbitmq-data:
  minio-data:
