version: v0.13.0

dsn: memory

serve:
  public:
    base_url: https://pixeleye-kratos.zu.ca/
    cors:
      enabled: true
  admin:
    base_url: https://pixeleye-kratos-admin.zu.ca/

selfservice:
  default_browser_return_url: https://pixeleye-frontend.zu.ca/
  allowed_return_urls:
    - https://pixeleye-frontend.zu.ca

  methods:
    password:
      enabled: true
    # oidc:
    #   config:
    #     providers:
    #       - client_id: CHANGE_ME
    #         client_secret: CHANGE_ME
    #         id: github
    #         label: github
    #         mapper_url: file:///etc/config/kratos/github.jsonnet
    #         provider: github-app
    #         scope: []
    #   enabled: true

  flows:
    error:
      ui_url: https://pixeleye-frontend.zu.ca/auth-error

    settings:
      ui_url: https://pixeleye-frontend.zu.ca/settings/account
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: https://pixeleye-frontend.zu.ca/recovery
      use: code

    verification:
      enabled: true
      ui_url: https://pixeleye-frontend.zu.ca/verification
      use: code
      after:
        default_browser_return_url: https://pixeleye-frontend.zu.ca/dashboard

    logout:
      after:
        default_browser_return_url: https://pixeleye-frontend.zu.ca/login

    login:
      ui_url: https://pixeleye-frontend.zu.ca/login
      lifespan: 10m
      after:
        default_browser_return_url: https://pixeleye-frontend.zu.ca/dashboard

    registration:
      lifespan: 10m
      ui_url: https://pixeleye-frontend.zu.ca/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui
        oidc:
          hooks:
            - hook: show_verification_ui
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
